[package]
name = "rs-autofixture-tests"
version = "0.5.0"
edition = "2024"
publish = false

[dependencies]
rs-autofixture = { path = "../autofixture", features = ["derive", "chrono", "uuid-extra", "lettre", "rust-decimal", "tokio"] }
chrono = "0.4"
lettre = "0.11"
paste = "1.0"
rust_decimal = { version = "1.42" }
tokio = { version = "1", features = ["sync", "rt", "macros"] }
uuid = "1.0"
